name: Java CI with Gradle

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: release version
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Build
      run: ./gradlew build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: build/libs
    - name: Publish
      if: github.ref == 'refs/heads/master'
      run: ./gradlew publish
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
    - name: Release
      if: github.event_name == 'workflow_dispatch'
      run: |
        # GPG_SECRET_KEYS created with: gpg --export-secret-keys --armor
        echo ${{secrets.GPG_SECRET_KEYS}} | gpg --import --armor --no-tty --batch --yes
        git config --local user.email "candrews@integralblue.com"
        git config --local user.name "Craig Andrews (GitHub Actions)"
        git config --local user.signingKey ${${{secrets.GPG_KEY_ID}}: -8}
        git config --local commit.gpgsign true
        git config --local user.signingkey ${{secrets.GPG_KEY_ID}}
        gpg --keyring secring.gpg --export-secret-keys > .gnupg/secring.gpg
        ./gradlew release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${{ github.event.inputs.releaseVersion }} -Psigning.secretKeyRingFile=.gnupg/secring.gpg -Psigning.keyId=${${{secrets.GPG_KEY_ID}}: -8} -Psigning.password=
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
