name: Java CI with Gradle

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: release version
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Set Up Signing
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/master'
      run: |
        echo '${{secrets.GPG_SECRET_KEYS}}' | gpg --import --armor --no-tty --batch --yes # GPG_SECRET_KEYS created with: gpg --export-secret-keys --armor
        gpg --export-secret-keys > ~/.gnupg/secring.gpg
        git config --local user.email "candrews@integralblue.com"
        git config --local user.name "Craig Andrews (GitHub Actions)"
        git config --local user.signingKey "${GPG_KEY_ID: -8}"
        git config --local commit.gpgsign true
        git config --local user.signingkey "${GPG_KEY_ID}"
        echo "signing.secretKeyRingFile=.gnupg/secring.gpg" >> ~/.gradle/gradle.properties
        echo "signing.keyId=${GPG_KEY_ID: -8}" >> ~/.gradle/gradle.properties
        echo "signing.gnupg.useLegacyGpg=true" >> ~/.gradle/gradle.properties
        echo "signing.password=" >> ~/.gradle/gradle.properties
      env:
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
    - name: Build
      run: ./gradlew build
    - name: Publish
      if: github.ref == 'refs/heads/master'
      run: |
        ./gradlew publish
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
    - name: Release
      if: github.event_name == 'workflow_dispatch'
      run: |
        ./gradlew release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${{ github.event.inputs.releaseVersion }}
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: build/libs
